### ISSUE TITLE
set Anchor depend on position on screen area

### ISSUE THREAD

**Issue by dutrieux** [ketho-wow/ModernQuestWatch#2]
Hello, 

Thx for adding the movable with alt-clicking, but now when we add a new quest to track, the position is not fixed and the tracker is growing on the top and the bottom and the left and the right.

It will nice is the anchor is set depending where the tracker is set : 

- on the right-top corner if the tracker is placed on right-top of screen area
- on the right-bottom corner if the tracker is place on right-bottom of the screen area
...

![image](https://user-images.githubusercontent.com/1622751/62848988-173ac580-bcde-11e9-80c3-3fa769b2296c.png)

Best regards

Duto

**Comment by Ketho** [comment]
That's some nice editing in the image. I will set the anchors depending on the tracker location
I also messed up the default anchors when adding the mover 😖

**Comment by Ketho** [comment]
> the position is not fixed and the tracker is growing on the top and the bottom and the left and the right.

The position is fixed now `SetPoint("TOPRIGHT")` in 1.0.8 and the tracker is growing to the bottom and the left

I have not yet set the anchor depending where the tracker is set, which would be nicer

**Comment by Ketho** [comment]
https://github.com/ketho-wow/ModernQuestWatch/commit/3c318ca5dabb3d6e5f8831a5a849935ac8d1c84f
